/**
 * Configuration for the Dev Diary system
 * Using Next.js built-in environment variables support
 */
export const config = {
  // OpenAI configuration
  openai: {
    apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY || '',
  },
  
  // Notion configuration
  notion: {
    apiKey: process.env.NEXT_PUBLIC_NOTION_API_KEY || '',
    databaseId: process.env.NEXT_PUBLIC_NOTION_DATABASE_ID || '',
    enabled: !!process.env.NEXT_PUBLIC_NOTION_API_KEY && !!process.env.NEXT_PUBLIC_NOTION_DATABASE_ID,
  },
  
  // GitHub configuration
  github: {
    token: process.env.NEXT_PUBLIC_GITHUB_TOKEN || '',
    enabled: !!process.env.NEXT_PUBLIC_GITHUB_TOKEN,
  },
  
  // Telegram configuration
  telegram: {
    token: process.env.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN || '',
    chatId: process.env.NEXT_PUBLIC_TELEGRAM_CHAT_ID || '',
    enabled: !!process.env.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN && !!process.env.NEXT_PUBLIC_TELEGRAM_CHAT_ID,
  },
  
  // Pieces configuration
  pieces: {
    baseUrl: process.env.NEXT_PUBLIC_PIECES_BASE_URL || 'http://localhost:1000',
    apiKey: process.env.NEXT_PUBLIC_PIECES_API_KEY,
    enabled: true, // Always enabled, with or without API key
  },
  
  // Git configuration
  git: {
    repositoryPath: process.env.NEXT_PUBLIC_GIT_REPOSITORY_PATH || process.cwd(),
    enabled: !!process.env.NEXT_PUBLIC_GIT_REPOSITORY_PATH,
  },
  
  // Application configuration
  app: {
    autoGenerateDaily: process.env.NEXT_PUBLIC_AUTO_GENERATE_DAILY === 'true',
    autoPublish: process.env.NEXT_PUBLIC_AUTO_PUBLISH === 'true',
    enableActivityLogging: process.env.NEXT_PUBLIC_ENABLE_ACTIVITY_LOGGING === 'true',
  },
};

export default config;